version: '3.8'

services:
 web:
  image: personalinfo
  ports:
  - 8000:5000
  volumes:
  - ./:/app
  depends_on:
  - mysqldb

 mysqldb:
  container_name: mysqldb
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

      